### ISSUE TITLE
[Sickle cell] Visit schedule for baseline

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/jss-sickle-cell-screening#11]
https://docs.google.com/spreadsheets/d/1JcHQ-VmLYy19pdKYW2j71CiglS3XYYABRtK3DQq6vak/edit#gid=930381891

**Comment by garimadosar5** [comment]
QA Notes-  
- Baseline form is scheduling for all type of genotype. It should schedule only in case of disease. -
Now Form is not getting schedule but "Save and proceed to baseline" button is there.
![Screen Shot 2020-03-27 at 7.21.55 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/fa9a3466-4689-4e37-a999-0ddf63eaa177)

- If genotype comes from the lab result flow, it does not schedule the baseline form.  **This is not fixed checked for a new case.**
![Screen Shot 2020-03-27 at 7.37.45 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/c4a00e3f-71d1-4e60-86b1-32bb8f0254a7)

New Case 
![Screen Shot 2020-03-31 at 10.44.46 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/d1b1a22b-767e-47d8-b0d6-036afb86ea14)

**Comment by nupoorkhandelwal** [comment]
@garimadosar5 Can u please mention the details of any one test case.bcoz i am trying it on staging and its working for the disease only. ie. SS or Beta thal or S-Beta Thal

@garimadosar5  The case "jaya bharti" seems to be not correct, as there is no encounter capturing the genotype and still  the program summary is displaying it.Please check

Please test with some other individual and let me know the exact issue.

**Comment by nupoorkhandelwal** [comment]
![screenshot-2020-03-31_18.00.41.72.png](https://images.zenhubusercontent.com/5d1469c9b0b5db61870d0f5c/8d9f1be0-5221-4fcd-a526-8b5be4507c20)![screenshot-2020-03-31_18.00.34.101.png](https://images.zenhubusercontent.com/5d1469c9b0b5db61870d0f5c/d9519c90-fa80-4e53-a2fe-77b4a0d3c62a)
