### ISSUE TITLE
[Sickle Cell][Report] Lab Test schedule report

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/jss-sickle-cell-screening#16]
https://docs.google.com/spreadsheets/d/1JcHQ-VmLYy19pdKYW2j71CiglS3XYYABRtK3DQq6vak/edit#gid=1391170315

**Comment by garimadosar5** [comment]
QA Notes - 
- Start and end date are missing.
- Put the date on the scheduled date.

**Comment by sachsk** [comment]
@garimadosar5 
Added date filter on schedule date
