### ISSUE TITLE
[JSCS] Change in Ind. Reg form

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/jss-sickle-cell-screening#31]
**Ref Doc -** https://docs.google.com/document/d/1NqiJL46zt5BcDi-Jf4o_sBd_ZpRf2dwy-pYJj5ZvSfM/edit#

 1. First Name + Last Name = Full Name
2. Last Name= Caste Name.

3. Data Migration is needed.
1. In case Caste data is not available (around 2151), do not move last name to first name.
2. In case Last name is NA, do not move that to first name.
- Remove question Caste (Free Teaxt)

- Add one more question "type of person screened".
https://docs.google.com/document/d/18-CZWq-9iM0fEieNjWXzKpMDacL6zOm5BsLAfTcsNio/edit
Point 5

**Comment by vindeolal** [comment]
- Form and translation changes are done in JSCS UAT org introduction.
- Migration script is given for review. https://github.com/avniproject/jss-sickle-cell-screening/blob/master/migrations/UpdateFirstNameAndLastName.sql
 
-----Production activity-----
- import the bundle from UAT org
- Import the translations

-- Migration related activities--- 
- Ask all the users to sync their data and get time slot to run the migration.
- Sync all the data in our device.
- run the migration script.
- Sync again and setup the fast sync.
- ask users to sync.
