### ISSUE TITLE
[JSCS][Report] Form extract report form Sickle cell testing data collection

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/jss-sickle-cell-screening#32]
https://docs.google.com/spreadsheets/d/155tFDCBUxiHRgS-gVg-rCMc0HeInxSF4o2qa392GzAE/edit#gid=1169464774&range=1:1

**Comment by vindeolal** [comment]
The report is pointing to JSCS UAT org
link: https://reporting.avniproject.org/question/1629
The same report is kept for Dindori as well https://reporting.avniproject.org/question/1635

**Comment by garimadosar5** [comment]
**QA Notes -** 
- There is no report for registration of Lab facility.

**Comment by vindeolal** [comment]
@garimadosar5 both the reports are merged. You can see the registration data as well in the same report. Do we need separate report for registration? It just have name and location.

**Comment by vindeolal** [comment]
Report link https://reporting.avniproject.org/question/1641
