### ISSUE TITLE
[JSCS][Report] District wise Screening data

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/jss-sickle-cell-screening#33]
Ref doc - https://docs.google.com/spreadsheets/d/155tFDCBUxiHRgS-gVg-rCMc0HeInxSF4o2qa392GzAE/edit#gid=1169464774&range=6:6

**Comment by vindeolal** [comment]
Report is pointing to JSCS UAT
link : https://reporting.avniproject.org/question/1632
The same report is kept for Dindori as well https://reporting.avniproject.org/question/1633
