### ISSUE TITLE
[JSCS][Report] Lab wise screening data

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/jss-sickle-cell-screening#34]
Ref Doc - https://docs.google.com/spreadsheets/d/155tFDCBUxiHRgS-gVg-rCMc0HeInxSF4o2qa392GzAE/edit#gid=1169464774&range=16:16

**Comment by vindeolal** [comment]
Report is pointing to JSCS UAT
link : https://reporting.avniproject.org/question/1631
The same report is kept for Dindori as well https://reporting.avniproject.org/question/1634

**Comment by garimadosar5** [comment]
**QA Notes -** 
- Do we need to put lab-related reports in each district separately?
