### ISSUE TITLE
[JSCS][Report] User wise daily screening data (With Month filter) in following format 

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/jss-sickle-cell-screening#37]
**Doc-** https://docs.google.com/document/d/18-CZWq-9iM0fEieNjWXzKpMDacL6zOm5BsLAfTcsNio/edit

Point 9 in the document.

**Comment by vindeolal** [comment]
Report link: https://reporting.avniproject.org/question/1660

**Comment by garimadosar5** [comment]
**QA Notes -** 
- We might want to add a total row at last.
- Remove our usernames (from samanvay). like nupoor, hiren, vivek, pradipta etc.

**Comment by garimadosar5** [comment]
QA Notes- 2
- What data is showing when no filter is applied. I think this filter should be mandatory. change accordingly.
