### ISSUE TITLE
[JSCS][Report] User-wise monthly baseline & follow-up form filling information. 

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/jss-sickle-cell-screening#38]
Doc - https://docs.google.com/document/d/18-CZWq-9iM0fEieNjWXzKpMDacL6zOm5BsLAfTcsNio/edit

Point 10 in document.

**Comment by vindeolal** [comment]
Report link: https://reporting.avniproject.org/question/1661

Please note that in document columns are given as month wise but as discussed it'll be same as other report and will have day-wise data for selected month

These Samanvay users are removed from the report
```
                      'joy@jscs',
                       'pradipta@jscs',
                       'nupoork@jscs',
                       'vinodd@jscs',
                       'hiren@jscs',
                       'arjunk@jscs',
                       'viveks@jscs',
                       'sachink@jscs',
                       'garimad@jscs',
                       'vinay@jscs'
```

**Comment by garimadosar5** [comment]
**QA Notes -** 
- What data is showing when no filter is applied.
Shall we make the filter mandatory?
