### ISSUE TITLE
[JSCS] UAT feedback on Govt lab facility module | App.

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/jss-sickle-cell-screening#41]
**Ref Doc** - https://docs.google.com/document/d/1NqiJL46zt5BcDi-Jf4o_sBd_ZpRf2dwy-pYJj5ZvSfM/edit#
From Page 5.
**App Feedback**
- [x] Name of the form should be changed.
Change - Registration form name should be "Government Lab Facility Registration".
Change - Encounter "Sickle cell testing entry Ehttps://reporting.avniproject.org/question/1629-do-not-use-data-extract-government-lab-facility-sickle-cell-testing-entryncounter" to "Govt facilities lab's data of sickle cell"
- [x] Order of questions in registration form should be - District (Single select)-> Block (Single select) -> Type of facility (Single select)-> village / city name
- [x] Add these type of facility in the reports as column and filter.
https://reporting.avniproject.org/question/1641-do-not-use-data-extract-government-facilities-laboratory-registration

 - [x] District name options should be shown (All locations needs to be given by Rahul)
- [x] Block name options should be shown (All locations needs to be shared by Rahul)
- [x] type of facility options are (This question needs to be added)- 
Options - 
1. District Hospital, 
2. Civil Hospital, 
3. Community Health Center,  
4. Primary Health Center, 
5. Sub-Health Center, 
6. Other (text field option on selecting this)
 - [ ] Village / City (should be a text field) (not required now)
- [x] Forms of future months are being scheduled in this month - For example, August Month's form is being scheduled today after filling the form for July month. For the current month, it should be scheduled after the 25th of the current month. because the data would be of last month. Current scheduling logic will result into errors in data.
As I can see this form is visible in the registration section, so will it be visible to everyone who has access to the registration section or admin can give access of it to only selected users?
- Add a validation, If visit date is before scheduled date, it should give error.
- In lab testing data general encounter, Add an option data not available. It will schedule next months' encounter. They can go back and edit the form whenever data is available. (COnfirm with Rahul)
- [x] Catchment area of each user should be only a particular lab which was assigned to him. He/she shouldn't be able to edit the data of other facilities.
- [ ] For the above point, can we make some users (we call them lab mentors & SS Coordinator) who have access to data entry of all facilities with one single login? (these users will have master catchment)
- [ ] Home page of the users should be the profile of the lab, or the link of the profile of labs.
Dashboard is of no use in this case. -It can not be done using current features. It is product change, will require additional budget. (this is not done, not possible right now may be we can have a custom dashboard)

**Comment by vindeolal** [comment]
@garimadosar5 There are some points which are not required and some which are not possible. I have updated it against each item.

**Comment by garimadosar5** [comment]
**QA Notes** - 
- Registration form name change is not reflecting on the registration page.
![Screenshot_2021-09-18-21-28-34-48_e67de974eab1ae435bf1faa372eb4549.jpg](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/fd497c0c-f228-45fa-9eba-b35df83cad5f)
- facility type is showing only "Other".
![Screenshot_2021-09-19-18-11-13-26_e67de974eab1ae435bf1faa372eb4549.jpg](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/c571f432-91de-4a88-93d8-a2fb83fc47ae)

**Comment by vindeolal** [comment]
- Changing registration form name will not change subject type name.
- We autoselect type of facility based on the location selected. Right now in the rule it is mentioed for some specific locations
`    'District Hospital': ['Anuppur'],
    'Civil Hospital': [],
    'Community Health Center': ['Parasi', 'Rajendragram', 'Jaithari'],
    'Primary Health Center': ['Funaga', 'Amarkantak', 'Karpa'],
    'Sub Health Center': [],
    'Other': []
`
If none of these locations will be selected then it'll show Other.
For the lab module I suggest you should use labuser@jscsuat or change your chatchment to Anuppur Lab
