### ISSUE TITLE
[JSCS] UAT feedback on Govt lab facility module | Report.

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/jss-sickle-cell-screening#42]
**Ref Doc -** https://docs.google.com/document/d/1NqiJL46zt5BcDi-Jf4o_sBd_ZpRf2dwy-pYJj5ZvSfM/edit#
Page 5 onwards.

- [x] Report no. 1629 (Data extract - Government lab facility Sickle cell testing entry) - 
- Need the column of Month
- Need to add 4 more columns of sum -
1. Sum of screened persons - (Pregnant + Non pregnant)
2. Sum of Solubility Positive - (Pregnant + Non pregnant)
3. Sum of AS - (Pregnant + Non pregnant)
4. Sum of AS - (Pregnant + Non pregnant)
- Need a Filter of “Month”
- Need a Filter of “Lab Name”
- Need a Filter of “District”
- Need a Filter of “Block”
- [x] Report no. 1641(Government Lab facility registration) -
- Name of report should be "Govt facilities laboratory registration"
- Column named "First name" should be changed to "Lab Name"
1. Need columns of “District”
2. Need columns of “Block”
3. Need column of “Facility type”
- Need Filters of District, Block, facility type
- List should be sorted based on the registration date & time
- [x] Report no. 1631 (Government Lab Facility wise sickle cell data) -
- Current Filter of date range is for the submission date, while we need filter of the date/month of the data. 
- List should be sorted in alphabetical order of the lab name
- [x] Report no. 1632 (District wise Government sickle testing data) -
- List should be sorted in alphabetical order of the district name.
- Current Filter of date range is for the submission date, while we need filter of the date/month of the data. 
- [x] Report no. 1660 (User wise daily screening data) - 
- Need to add two columns 
1. Total registration - User wise Sum of registration done in that month
2. Total Enrollment - User wise sum of enrolments done in that month
These two columns should be the 2nd & 3rd columns, so that we do not need to scroll all the columns. 
- First column (Users) should be a frozen column so that we can easily check the data after scrolling. [**This is not supported in metabase, you can download the excel and do it over there**]
- Currently this report is showing for all the users registered in all catchments. So we also need the same report for each catchment in the catchment’s collection. 
- Since this report contains two types of data, can we get alternate colours in alternate columns? [**DONE**]
- [x] Report no. 1661 (User wise daily baseline & follow-up form filling information) - 
- Need to add two columns 
1. Total Baseline - User wise Sum of baseline forms filled in that month
2. Total Followup - User wise Sum of followup forms filled in that month
These two columns should be the 2nd & 3rd columns, so that we do not need to scroll all the columns. 
- First column (Users) should be a frozen column so that we can easily check the data after scrolling. [**This is not supported in metabase, you can download the excel and do it over there**]
- Currently this report is showing for all the users registered in all catchments. So we also need the same report for each catchment in the catchment’s collection. 
- Since this report contains two types of data, can we get alternate colours in alternate columns? [**DONE**]

**Comment by vindeolal** [comment]
Column “Facility type” and “Facility type”  filter are not added as it depends on another card. Please add this change to the same card or put this card on hold.

**Comment by garimadosar5** [comment]
**QA Notes -** 
https://reporting.avniproject.org/question/1629
- Point 1. Here Month and year is the month for which the data is filled not the month when data is filled. Need to correct this. - **NOT DONE**
- Same for Month filter
https://reporting.avniproject.org/question/1631
- Encounter month filter, change this to the filter with the month for  which the data is filled.
https://reporting.avniproject.org/question/1632
- Encounter month filter, change this to the filter with the month for  which the data is filled.

**Comment by vindeolal** [comment]
@garimadosar5 
I have fixed the logic by subtracting 1 month from the scheduled date. Will they do any unplanned visits? I think we should hide unplanned for this encounter, otherwise, it will be difficult to capture for which month the data is being captured.

**Comment by garimadosar5** [comment]
@vindeolal 
Yes, we should hide this. but there are some scenarios where unplanned is required but that will be filled by another set of users. (kind of supervisor to the field workers)

Need to confirm what will happen to unplanned visits before we move this to done.

**Comment by vindeolal** [comment]
@garimadosar5 fixed it for unplanned visits as well, as they'll capture the data for previous month so in case of unplanned visit we can subtract 1 mont from the encounter date.
