### ISSUE TITLE
[JSCS] UAT feedback for Baseline and Followup forms

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/jss-sickle-cell-screening#43]
**Feedback doc -** 
https://docs.google.com/document/d/1NqiJL46zt5BcDi-Jf4o_sBd_ZpRf2dwy-pYJj5ZvSfM/edit#
Page 7 onwards.

**Baseline form**
**Requirement doc -** 
https://docs.google.com/spreadsheets/d/1JcHQ-VmLYy19pdKYW2j71CiglS3XYYABRtK3DQq6vak/edit#gid=0

- [x] Question “New contact no. of patient” is missing, it’s the first question in the sheet provided for the baseline form. Please add this question. 
- [x] FEG - Physical Pain -
Question - "How Many TImes from Childhood till now ?" this number should be more than "How many times in last 1 year ?"
- [x] On the page of Medicine and doses - After selecting “other medicine” option it is not showing next 2 questions - 
Start Date of Other Medicine
Is it regular ?
- [x] Data extract report is not working in metabase - Longitudinal export is not usable for him. 

**Followup form**
**Requirement doc -** 
https://docs.google.com/spreadsheets/d/1JcHQ-VmLYy19pdKYW2j71CiglS3XYYABRtK3DQq6vak/edit#gid=118032723
- [x] In the question of “No. of pain episodes in last 3 months”, If pain episodes in the last 3 months are = 0 then the questions “1. How many pain episodes were severe?” & “2. Pain SItes” shouldn’t be shown. 
- [x] Need to change the Order of one question in the “Problems” page “Any Problem  Any Other  Physical deformity / confirmed diagnosis or probable)”. This question should be asked after “Difficulty in walking (AVN / Chronic Painin hip)” & “Explain difficulty”.
- [x] In the section “Medicine & Doses” - After selecting the option of “other medicine” it is not asking following 3 questions -
- Name of Other Medicine
- Daily dose of Other Medicine
- Is it regular ?
- [x] Section “Support Group” - Option “beginner” is missing in the question. - **DONE**
- [x] Data extract report is not working in Metabase.

**Comment by garimadosar5** [comment]
**QA Notes -** 
**Baseline Form -** 
In the question of “No. of pain episodes in last 1 year” = 0 then the questions 
“1. How many pain episodes were severe?” & 
“2. Pain SItes” shouldn’t be shown.
- Question - "How many pain episodes were severe?" should not have more than "How many pain episodes in last 1 year?"

**Followup Form** 
- Explain difficulty question is missing from the page "problems"
 
**Form Extract -** 
- Move to production

**Comment by vindeolal** [comment]
@garimadosar5 
- Baseline form changes fixed.
- Followup form Explain difficulty is shown only when Difficulty in walking (AVN / Chronic Pain in hip) * is yes.
- Will Rahul not test reports on UAT? We can move it to prod once he approves it.
