### ISSUE TITLE
Production deployment.

### ISSUE THREAD

**Issue by vindeolal** [avniproject/jss-sickle-cell-screening#48]
These new changes will get deployed to the production,
1. Baseline and follow-up changes.
2. New lab facility subject type and its encounter.

Tech tasks,
1. Get the bundle from UAT org and deploy it to production.
2. Create the locations(if required), users, and catchments from https://docs.google.com/document/d/1NqiJL46zt5BcDi-Jf4o_sBd_ZpRf2dwy-pYJj5ZvSfM/edit# (location and user upload)
3. Register facility to above-provided locations. (subject upload)
4. All the above users will not have any registration privilege. Create two more, user groups, field users, and admin.
filed users will have access to the only individual subject types and the admin will have all privileges.
5. Put all the old users into the Filed user group. New users will be part of Lab user group.

**Comment by nupoorkhandelwal** [comment]
Uploades data -
https://drive.google.com/drive/folders/1NAfkrib-Wc00tAg2wdvIZ8uVslYVUw_f
