### ISSUE TITLE
Dindori data migration

### ISSUE THREAD

**Issue by vindeolal** [avniproject/jss-sickle-cell-screening#49]
Ticket details https://avni.freshdesk.com/a/tickets/1302.
Original sheet: https://docs.google.com/spreadsheets/d/1DR2Mykn0XYEtMaQDSqkUBIFSwXeYNqAYg4glnsmhklw/edit#gid=605314540
Formated sheet: https://docs.google.com/spreadsheets/d/10tpqwDQ7xQ4lYsH0ncOd8VOLk1Yf5At8ozpWXfYgCpI/edit#gid=0
Everything is done except fixing the villages from the main sheet. If that village does not exists in the system we'll need to create it via upload.

**Comment by sachsk** [comment]
Tasks done:

- [x] Upload registration

- [x] Upload enrolment

- [x] Upload Base screening data

- [x] Upload lab result entry

- [x] Scheduled baseline visits for individual with SS genotype which we have uploaded (97)
