### ISSUE TITLE
Move UAT reports to production.

### ISSUE THREAD

**Issue by vindeolal** [avniproject/jss-sickle-cell-screening#54]
- Change the DB to prod DB.
- Create the required views for the filter.
- https://reporting.openchs.org/question/1629-do-not-use-data-extract-government-facilities-labs-data-of-sickle-cell
- https://reporting.openchs.org/question/1632-do-no-use-summary-district-wise-government-sickle-testing-data
- https://reporting.openchs.org/question/1631-do-no-use-summary-government-lab-facility-wise-sickle-cell-testing-data
- https://reporting.openchs.org/question/1629-do-not-use-data-extract-government-facilities-labs-data-of-sickle-cell

**Comment by sachsk** [comment]
Moved to production.
@garimadosar5  Please remove "Do not use" from the name of the report once ready to deploy.

**Comment by garimadosar5** [comment]
**QA Notes -** 
@sachsk Please discuss following with Vinod and do the needful.
- Reports on UAT and not moved to prod - 
https://reporting.openchs.org/question/1641-do-not-use-data-extract-government-lab-facility-registration
- Why this collection has Not final tag - https://reporting.avniproject.org/collection/365-reports-not-final
- 4 reports in this collection are marked as Do Not Use
https://reporting.avniproject.org/collection/273-sickle-cell-dindori-jss-mp
- Do not use collection - 
https://reporting.avniproject.org/collection/302-do-not-use-sickle-cell-data-extract
- In process collection
https://reporting.avniproject.org/collection/364-do-not-use-reports-in-process
