### ISSUE TITLE
Lab facility feedback comments

### ISSUE THREAD

**Issue by vindeolal** [avniproject/jss-sickle-cell-screening#56]
Check the feedback comments on the ticket https://avni.freshdesk.com/a/tickets/1591

- Sickle cell testing entry should be scheduled one month before the reg date.
- Why for the lab user SS data is showing. (anuppur_dh@jscs)
- Check total entries count.
- Add new summary fields to the subject summary.
- For the completed visits check why the encounter name is not displaying.
- Check the address not displayed on the profile page of the lab.

**Comment by sachsk** [comment]
1.  Changed the visit scheduling added maxDate as earliestDate + 45 days
2. Checked the offline dashboard it's showing correct numbers. I think they need to reinstall the app once or clear app data.
3. checked the total entry count in offline dashboard showing correct numbers 
4. added summary fields
5. App is showing correct enc names as per rule.
6. Addresses are displayed under the subject name

**All changes are on UAT**

**Comment by garimadosar5** [comment]
**QA Notes -** 
- What fix is done for point 2. **We didn’t fix anything. its query from client we have checked it and its working fine**
- when editing unplanned visit,it is giving invalid date error. If unplanned is not required, hide the button. 
Or if unplanned is required then do not try to schedule any visit on unplanned visit.
**Hided unplanned**
