### ISSUE TITLE
[JSCS] Move Anuppur reports to use ETL

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/jss-sickle-cell-screening#64]
https://docs.google.com/spreadsheets/d/15U3mOkcVjHhXlr318uj8DRQNzC6mBOTf-GEPf9SLfTM/edit#gid=1653652164

**Comment by AchalaBelokar** [comment]
- [ ] Line list of all registered Beneficiaries vs  summary of sickle cell testing count mismatch 
1. Type not decided
2. hemoglobin genotype AA , SS,AS

- [x]  2. Line list of all registered Beneficiaries vs summary of sickle cell testing count vs  Line list of SS non anc mismatch

**Comment by AchalaBelokar** [comment]
- [x]  Line list of all registered Beneficiaries vs summary of sickle cell testing count mismatch
   1. positive solubility
