### ISSUE TITLE
[Support] Upload Base screening sickle cell encounter #1865

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/jss-sickle-cell-screening#66]
https://avni.freshdesk.com/a/tickets/1865

- [x] Upload Sickle Cell Screening encounter for individuals having following Enrolment Number s- 
CN00011, CN00012, CN00013, CN00014, CN00015, CN00016, CN00017, CN00018, CN00019, CN00020

Data for upload is available in this sheet --
https://docs.google.com/spreadsheets/d/10tpqwDQ7xQ4lYsH0ncOd8VOLk1Yf5At8ozpWXfYgCpI/edit#gid=885373821

**Comment by AchalaBelokar** [comment]
CN00017  Base screening form is not visible 
CN00020  is not visible Base screening
