### ISSUE TITLE
[JSCS] Update remaining reports to ETL

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/jss-sickle-cell-screening#67]
https://docs.google.com/spreadsheets/d/15U3mOkcVjHhXlr318uj8DRQNzC6mBOTf-GEPf9SLfTM/edit#gid=1653652164

**Comment by utkarshavni** [comment]
https://app.zenhub.com/workspaces/avni-5cf8e458bf08585333fd64ac/issues/avniproject/jss-sickle-cell-screening/63

Closing as duplicate card created above.
