### ISSUE TITLE
[JSCS] Update the digital signature

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/jss-sickle-cell-screening#74]
**Support ticket** - https://avni.freshdesk.com/a/tickets/2873

- [ ] Update the signature in the report card and diagnostic card as shared in the ticket.

Technical Approach -
1. Upload the shared image to - https://github.com/avniproject/jss-sickle-cell-screening/tree/master/extensions/prints
2. Replace the **img src** name to the new image name added for Annupur only - 
 - https://github.com/avniproject/jss-sickle-cell-screening/blob/8aef8ca0992c4543b99d13a534deb9ed0a3a8af0/extensions/prints/ssCard.html#L232
 - https://github.com/avniproject/jss-sickle-cell-screening/blob/8aef8ca0992c4543b99d13a534deb9ed0a3a8af0/extensions/prints/dignosticCard.html#L292
3. Create a zip named as "Archive.zip" and then upload it to the Extensions in JSCS org 
4. Test it with the option available on DEA in the same org

**Comment by vedfordev** [comment]
ETC from Taqi :- 30mins
