### ISSUE TITLE
[JSCS UAT] Void duplicate concept used on UAT

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/jss-sickle-cell-screening#75]
## Reference report - 
https://reporting.avniproject.org/question/1536-duplicate-concepts-in-a-form-production

Currently, there are two "Registration number" concepts getting used under "Lab results entry" form on UAT, we need to discard one.

## Tech taks
- [x] Compare the form element "Registration number" in "Lab results entry" form in UAT and prod
- [x] Now mark the one in UAT which is not the corresponding entry in prod org.

**Comment by vedfordev** [comment]
## Notes

from below query find out that we need to remove form elemet which has uuid = "35cc3efc-a0db-4350-82ca-e6d28e6772de" and display_order = 8

```
select fe.*
from form f
join form_element_group feg on f.id = feg.form_id
join form_element fe on feg.id = fe.form_element_group_id
where f.is_voided = false
and feg.is_voided = false
and fe.is_voided = false
and f.name = 'Lab results entry' and fe.name = 'Registration number'
order by fe.display_order
;
-- 010a16b9-e4d7-4e06-8d4b-a9132514a6ce
```
