### ISSUE TITLE
Upload data to sickle cell registry

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/jss-sickle-cell-screening#76]
## Tasks list:
1. Convert registration data file into patient records
2. Split registration data list into batches, each batch has to be processed as follows
    1. Get token
    3. Post Patient registration data
    4. Store request and response to file
    5. Store patient_unique_id, sickle_id
3. Convert test data file into test records
4. Split test data list into batches, each batch has to be processed as follows
    1. Get token
    2. Retrieve sickle_id from db using patient_unique_id and set it in request object
    3. Post Patient test data
    4. Store request and response to file

### Drive folder with relevant docs: 
@vinayvenu has the files

**Comment by vinayvenu** [comment]
https://avni.freshdesk.com/a/tickets/3439

**Comment by himeshr** [comment]
We are currently blocked due to StagingSickelCell app responding with ErrorMsg: "Data could not Saved! due to duplicate record or server issue." for valid requests as well.

**Comment by mahalakshme** [comment]
In 2 things, the postman collection JSON is not inline with that of sickle cell API documentation:
1. the key name for qrcode is qr_code not qr-code - With this alone, the issue gets resolved
2. format of the registration date: It needs to be of the format 'YYYY-MM-DD' 

Some background info., that I came to know from a contacted person that might help in testing:
There is a unique contraint validation around the combination of NameOfPerson, SonDaughterOfWifeOf, MobileNo, Gender.

**Comment by himeshr** [comment]
Yes, using qr_code gets it to work. 
For patient "Gayatri Kewat" the sickle cell registration response is ,
```
{"Status":200,"Total":1,"Success":1,"fail":0,"Success_records":[{"Status":200,"Message":"Patient information is Successfully Saved .","sickle_id":"24712","patient_unique_id":"SJ00329"}]}
```

**Comment by himeshr** [comment]
> In 2 things, the postman collection JSON is not inline with that of sickle cell API documentation:
> 
> 1. the key name for qrcode is qr_code not qr-code - With this alone, the issue gets resolved
> 2. format of the registration date: It needs to be of the format 'YYYY-MM-DD'
> 
> Some background info., that I came to know from a contacted person that might help in testing: There is a unique contraint validation around the combination of NameOfPerson, SonDaughterOfWifeOf, MobileNo, Gender.

After making the above corrections, post of registration data goes through, but only when we specify "health_facility_id" as "424790" and "healthfacilitytype_id" as "5".

**Comment by mahalakshme** [comment]
@himeshr they are not reply via mail, so I suggest whoever is going to pickup contact the no mentioned in keeweb with name 'Sickle cell help'. Its not the Tapas contact that Vinay has.

**Comment by himeshr** [comment]
@vinayvenu  can this be marked as done.?
