### ISSUE TITLE
Add few rules and validation for some exiting questions

### ISSUE THREAD

**Issue by Gojo-Taqi** [avniproject/jss-sickle-cell-screening#79]
- Link to the ticket - https://avni.freshdesk.com/a/tickets/3510

- [x] Schedule "SCD Followup Jan 2024" encounter 3 months after completing baseline form.
- [x] The follow-up will keep happening in 3-month instances.
- [x] Add a skip logic rule on "Date of starting of Hydroxyurea" in the "SCD Followup Jan 2024" encounter, where if "Date of starting of Hydroxyurea" or "Start Date of Hydroxyurea" is defined in any of the previous encounters, then don't show up.
- [x] Add validation rule on "Baseline form" for "Start Date of Hydroxyurea" where it should not accept dates from the future.
- [x] After QA move the changes to production and mark the ticket as resolved.

**Comment by Dinesh2019** [comment]
- [ ] Sickle follow-up is not scheduled.
- [ ] if we didn't give the "Date of starting Hydroxyurea" in Baseline then in the follow-up user unable to select the date 

Refer video :

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNnh3QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--10a5d9b13921e2daccc2210b8b2268027e1e4f12/Screen%20Recording%202024-04-18%20at%201.09.17%E2%80%AFPM.mov)

**Comment by Gojo-Taqi** [comment]
@Dinesh2019 I was unable to find why it was behaving like that.
For now I have written the rule using js, and it seems to work now.
Moving it back to QA ready.

**Comment by Dinesh2019** [comment]
@taqi you can move the changes to prod
