### ISSUE TITLE
[Sickle Cell] Baseline form

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/jss-sickle-cell-screening#8]
https://docs.google.com/spreadsheets/d/1JcHQ-VmLYy19pdKYW2j71CiglS3XYYABRtK3DQq6vak/edit#gid=0

**Comment by garimadosar5** [comment]
QA Note - 
- In some numeric type question, empty () is showing in question.
![Screen Shot 2020-03-26 at 4.54.22 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/a143f09e-4571-4e71-a682-eee3ca992ed5)

- In food choices,  skip is not working for the question "specify other" . - **DONE**
- The question "Which food the patient is problem with?" is missing.- **DONE**
- The question "Which food the patient is problem with?" - skip is not working.

**Comment by nupoorkhandelwal** [comment]
@garimadosar5  The empty braces with the numeric concepts is coming as they have empty unit values.
We have created concepts using webapp UI, it will happen for all the numeric concepts having no units specified.
@nupoorkhandelwal This should not happen. Please talk to Arjun regarding this.

**Comment by garimadosar5** [comment]
QA Notes - 
- The question "Which food the patient is problem with?"  - Not fixed.
![Screen Shot 2020-03-30 at 9.37.05 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/d971d976-2f18-4bda-b96f-cc029c81cc56)
