### ISSUE TITLE
[Sickle cell] Followup form

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/jss-sickle-cell-screening#9]
https://docs.google.com/spreadsheets/d/1JcHQ-VmLYy19pdKYW2j71CiglS3XYYABRtK3DQq6vak/edit#gid=118032723

**Comment by garimadosar5** [comment]
QA Notes - 
- "Date of Start of Hydroxyurea Medicine" is showing even if answered once. Please check once. - **DONE**

**Comment by nupoorkhandelwal** [comment]
@garimadosar5 fixed this.
